import os
import sys
import subprocess

# Force stdout to UTF-8 to handle emojis/unicode on Windows
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')

# Auto-install Pillow if not present
try:
    from PIL import Image
except ImportError:
    print("Pillow library not found. Installing it automatically via pip...")
    try:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "Pillow"])
        from PIL import Image
    except Exception as err:
        print(f"Failed to install Pillow automatically: {err}")
        print("Please install it manually by running: pip install Pillow")
        sys.exit(1)

def optimize_photos():
    raw_dir = "raw_photos"
    out_dir = os.path.join("assets", "gallery")
    
    if not os.path.exists(raw_dir):
        os.makedirs(raw_dir)
        print(f"Created '{raw_dir}' folder. Please place your high-res (7MB - 30MB) photos in this folder.")
        print("Then run this script again to optimize them!")
        return

    if not os.path.exists(out_dir):
        os.makedirs(out_dir)

    raw_files = [f for f in os.listdir(raw_dir) if f.lower().endswith(('.png', '.jpg', '.jpeg', '.bmp', '.tiff'))]
    
    if not raw_files:
        print(f"No raw images found in '{raw_dir}/' folder.")
        print("Please copy your 7MB - 30MB photos into the 'raw_photos' folder and run this script again.")
        return

    print(f"Found {len(raw_files)} photos in '{raw_dir}'. Starting optimization...")
    print("-" * 60)
    
    total_raw_size = 0
    total_opt_size = 0
    
    for filename in raw_files:
        raw_path = os.path.join(raw_dir, filename)
        name_without_ext = os.path.splitext(filename)[0]
        opt_filename = f"{name_without_ext}.webp"
        opt_path = os.path.join(out_dir, opt_filename)
        
        raw_size = os.path.getsize(raw_path) / (1024 * 1024) # in MB
        total_raw_size += raw_size
        
        try:
            with Image.open(raw_path) as img:
                # Convert RGBA to RGB if saving to WebP
                if img.mode in ('RGBA', 'LA'):
                    img = img.convert('RGB')
                
                # Resize if larger than 1920px (standard fullscreen width)
                max_size = 1920
                width, height = img.size
                if width > max_size or height > max_size:
                    if width > height:
                        new_width = max_size
                        new_height = int((height / width) * max_size)
                    else:
                        new_height = max_size
                        new_width = int((width / height) * max_size)
                    
                    img = img.resize((new_width, new_height), Image.Resampling.LANCZOS)
                
                # Save optimized WebP
                img.save(opt_path, "WEBP", quality=80, optimize=True)
                
            opt_size = os.path.getsize(opt_path) / (1024 * 1024) # in MB
            total_opt_size += opt_size
            
            reduction = (1 - (opt_size / raw_size)) * 100
            print(f"✔ Compressed: {filename} ({raw_size:.2f} MB) -> {opt_filename} ({opt_size:.3f} MB) [{reduction:.1f}% reduction]")
            
        except Exception as e:
            print(f"❌ Failed to process {filename}: {e}")
            
    print("-" * 60)
    savings = (1 - (total_opt_size / total_raw_size)) * 100
    print(f"🎉 Optimization Complete!")
    print(f"📁 Raw Folder Size: {total_raw_size:.2f} MB")
    print(f"📁 Optimized Gallery Size: {total_opt_size:.2f} MB")
    print(f"⚡ Total Storage Saved: {savings:.1f}%!")

    # Write optimized photos data to javascript file
    js_path = os.path.join(out_dir, "photos-data.js")
    try:
        with open(js_path, "w", encoding="utf-8") as js_file:
            js_file.write("// Auto-generated by optimize_images.py\n")
            js_file.write("window.CORBETT_UPLOADED_PHOTOS = [\n")
            for i, fname in enumerate(raw_files):
                name_without_ext = os.path.splitext(fname)[0]
                opt_filename = f"{name_without_ext}.webp"
                # Determine nice caption based on filename patterns
                if name_without_ext.startswith("NAV"):
                    caption = f"Spectacular Corbett Wildlife & Jungle Vibe (Shot {name_without_ext}) 🐯"
                elif name_without_ext.startswith("VIN"):
                    caption = f"Nature Vista and Serene Wilderness Landscape (Shot {name_without_ext}) 🏞️"
                else:
                    caption = f"Stunning Glimpse of Jim Corbett National Park (Shot {name_without_ext}) 🌿"
                
                comma = "," if i < len(raw_files) - 1 else ""
                js_file.write(f'    {{ src: "assets/gallery/{opt_filename}", caption: "{caption}" }}{comma}\n')
            js_file.write("];\n")
        print(f"✔ Generated JS database at: {js_path}")
    except Exception as e:
        print(f"❌ Failed to write JS database: {e}")

    print(f"\n💡 You can now reference these optimized images inside your HTML files under path:\n   assets/gallery/filename.webp")

if __name__ == "__main__":
    optimize_photos()
